# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## Ma'lumotlar tahlili. Pandas kutubxonasi.

# **AMALIYOT**
## 3.1 Series va Index

### **1-mashq**. `Pandas` kutubxonasini `pd`, `numpy` kutubxonasini `np` deb chaqirib oling

In [221]:
# Javobni shuyerga yozing
import pandas as pd
import numpy as np

In [222]:
#@title To'g'ri javob
import pandas as pd
import numpy as np

### **2-mashq.** O'zbekiston Respublikasi viloyatlaridan iborat bir o'lchamli Series obyektini yarating

In [223]:
# Javobni shu yerga yozing
regions = ['Fargʻona','Toshkent','Samarqand','Buxoro','Surxondaryo',
 'Qashqadaryo','Xorazm','Namangan','Andijon','Jizzax',
 'Sirdaryo','Navoiy',"Qoraqalpog'iston Respublikasi"]
obj1 = pd.Series(regions)
print(obj1)

0                          Fargʻona
1                          Toshkent
2                         Samarqand
3                            Buxoro
4                       Surxondaryo
5                       Qashqadaryo
6                            Xorazm
7                          Namangan
8                           Andijon
9                            Jizzax
10                         Sirdaryo
11                           Navoiy
12    Qoraqalpog'iston Respublikasi
dtype: object

In [224]:
#@title **To'g'ri javob**
obj = pd.Series(
    [
        "Andijon",
        "Buxoro",
        "Farg'ona",
        "Jizzax",
        "Xorazm",
        "Namangan",
        "Navoiy",
        "Qashqadaryo",
        "Qoraqalpog'iston Respublikasi",
        "Samarqand",
        "Sirdaryo",
        "Surxondaryo",
        "Toshkent",
    ]
)
print(obj)

0                           Andijon
1                            Buxoro
2                          Farg'ona
3                            Jizzax
4                            Xorazm
5                          Namangan
6                            Navoiy
7                       Qashqadaryo
8     Qoraqalpog'iston Respublikasi
9                         Samarqand
10                         Sirdaryo
11                      Surxondaryo
12                         Toshkent
dtype: object

### **3-mashq.** Yuqorida yaratilgan Series obyektining barcha qiymaltarini chiqaring

In [225]:
# Javobni shuyerga yozing
obj1.values

array(['Fargʻona', 'Toshkent', 'Samarqand', 'Buxoro', 'Surxondaryo',
       'Qashqadaryo', 'Xorazm', 'Namangan', 'Andijon', 'Jizzax',
       'Sirdaryo', 'Navoiy', "Qoraqalpog'iston Respublikasi"],
      dtype=object)

In [226]:
# @title **To'g'ri javob**
obj.values

array(['Andijon', 'Buxoro', "Farg'ona", 'Jizzax', 'Xorazm', 'Namangan',
       'Navoiy', 'Qashqadaryo', "Qoraqalpog'iston Respublikasi",
       'Samarqand', 'Sirdaryo', 'Surxondaryo', 'Toshkent'], dtype=object)

### **4-mashq.** Yuqoridagi Series obyektining eng birinchi qiymatini chiqaring

In [227]:
# Javobni shuyerga yozing
obj1[0]

'Fargʻona'

In [228]:
# @title **To'g'ri javob**
obj[0]

'Andijon'

### **5-mashq.** Yuqoridagi Series obyektining eng oxirgi qiymatini chiqaring

In [229]:
# Javobni shuyerga yozing
obj1.iloc[-1]

"Qoraqalpog'iston Respublikasi"

In [230]:
obj1[12]

"Qoraqalpog'iston Respublikasi"

In [231]:
# @title **To'g'ri javob**
obj[12]

'Toshkent'

### **6-mashq.** Yuqoridagi Series obyekti uzunligini chiqaring

In [232]:
# Javobni shuyerga yozing
len(obj1)
obj1.size

13

In [233]:
# @title **To'g'ri javob**
obj.size

13

### **7-mashq.** Yuqoridagi Series obyektining o'rtasidan 3 ta qiymat chiqaring

In [234]:
# Javobni shuyerga yozing
obj1[5:8]

5    Qashqadaryo
6         Xorazm
7       Namangan
dtype: object

In [235]:
obj1[[5,6,7]]

5    Qashqadaryo
6         Xorazm
7       Namangan
dtype: object

In [236]:
# @title **To'g'ri javob**

obj[[5, 6, 7]]

5       Namangan
6         Navoiy
7    Qashqadaryo
dtype: object

### **8-mashq.** Quyidagi Series obyektini yarating.
**Ahamiyat bering. `Series` obyekti indeksi sifatida viloyatlar nomi ishlatilgan**

In [237]:
# @title
ind = obj.values
aholi = [
    1899000,
    1384700,
    2597000,
    910500,
    1200000,
    1862000,
    767500,
    2029000,
    1200000,
    2322000,
    648100,
    1676000,
    4450000,
]
obj2 = pd.Series(aholi, index=ind)
print(obj2)

Andijon                          1899000
Buxoro                           1384700
Farg'ona                         2597000
Jizzax                            910500
Xorazm                           1200000
Namangan                         1862000
Navoiy                            767500
Qashqadaryo                      2029000
Qoraqalpog'iston Respublikasi    1200000
Samarqand                        2322000
Sirdaryo                          648100
Surxondaryo                      1676000
Toshkent                         4450000
dtype: int64

In [238]:
# Javobni shuyerga yozing
obj2 = pd.Series([1899000, 1384700, 2597000, 910500, 1200000, 1862000, 767500,
                  2029000, 1200000, 2322000, 648100, 1676000, 4450000], index = regions)
print(obj2)

Fargʻona                         1899000
Toshkent                         1384700
Samarqand                        2597000
Buxoro                            910500
Surxondaryo                      1200000
Qashqadaryo                      1862000
Xorazm                            767500
Namangan                         2029000
Andijon                          1200000
Jizzax                           2322000
Sirdaryo                          648100
Navoiy                           1676000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64

### **9-mashq.** Yuqoridagi `Series` obyektidan Jizzax, Buxoro va Namangan viloyatlarining aholisini chiqaring

In [239]:
# Javobni shuyerga yozing

obj2[['Jizzax','Buxoro','Namangan']]

Jizzax      2322000
Buxoro       910500
Namangan    2029000
dtype: int64

In [240]:
# @title **To'g'ri javob**
obj2[["Jizzax", "Buxoro", "Namangan"]]

Jizzax      2322000
Buxoro       910500
Namangan    2029000
dtype: int64

### **10-mashq.** Yuqoridagi `Series` obyektidan aholi soni 1 milliondan kam va ko'p bo'lgan viloyatlarni alohida chiqaring

In [241]:
# Javobni shuyerga yozing
kop = obj2[obj2>1000000]
kop.index.name = "Aholisi 1 milliondan ko'p viloyatlar"
print(kop)

Aholisi 1 milliondan ko'p viloyatlar
Fargʻona                         1899000
Toshkent                         1384700
Samarqand                        2597000
Surxondaryo                      1200000
Qashqadaryo                      1862000
Namangan                         2029000
Andijon                          1200000
Jizzax                           2322000
Navoiy                           1676000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64

In [242]:
kam = obj2[obj2<1000000]
kam.index.name = "Aholisi 1 milliondan kam viloyatlar"
print(kam)

Aholisi 1 milliondan kam viloyatlar
Buxoro      910500
Xorazm      767500
Sirdaryo    648100
dtype: int64

In [243]:
# @title **To'g'ri javob**
print("Aholisi 1 milliondan ko'p viloyatlar")
print(obj2[obj2 > 1_000_000])
# Pythonda katta sonlarni yozishda 0 orasini _ bilan ajratish mumkin

Aholisi 1 milliondan ko'p viloyatlar
Fargʻona                         1899000
Toshkent                         1384700
Samarqand                        2597000
Surxondaryo                      1200000
Qashqadaryo                      1862000
Namangan                         2029000
Andijon                          1200000
Jizzax                           2322000
Navoiy                           1676000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64

In [244]:
# @title
print("Aholisi 1 milliondan kam viloyatlar")
print(obj2[obj2 < 1_000_000])

Aholisi 1 milliondan kam viloyatlar
Buxoro      910500
Xorazm      767500
Sirdaryo    648100
dtype: int64

### **11-mashq.** Aholisi 1 milliondan ko'p davlatlar orasida Navoiy viloyati bor/yo'qligini tekshiring

In [245]:
# Javobni shuyerga yozing
"Navoiy" in obj2[obj2>1_000_000]

True

In [246]:
# @title **To'g'ri javob**
"Navoiy" in obj2[obj2 > 1_000_000]

True

### **12-mashq.** Quyidagi lug'atda viloyatlar va ularning maydonlari berilgan. Lug'atdan yangi `Series` obyektini yarating va unga "Hududlar hajmi" deb nom bering

In [247]:
dictionary = {
    "Andijon": 4200,
    "Buxoro": 39400,
    "Farg'ona": 6800,
    "Jizzax": 20500,
    "Xorazm": 6300,
    "Namangan": 7900,
    "Navoiy": 110800,
    "Qashqadaryo": 28400,
    "Qoraqalpog'iston Respublikasi": 160000,
    "Samarqand": 16400,
    "Sirdaryo": 5100,
    "Surxondaryo": 20800,
    "Toshkent": 15300,
}

In [248]:
# Javobni shuyerga yozing
obj3 = pd.Series(dictionary)
obj3.name = 'Hududlar hajmi'
print(obj3)

Andijon                            4200
Buxoro                            39400
Farg'ona                           6800
Jizzax                            20500
Xorazm                             6300
Namangan                           7900
Navoiy                           110800
Qashqadaryo                       28400
Qoraqalpog'iston Respublikasi    160000
Samarqand                         16400
Sirdaryo                           5100
Surxondaryo                       20800
Toshkent                          15300
Name: Hududlar hajmi, dtype: int64

In [249]:
#@title To'g'ri javob
obj3 = pd.Series(dict)
obj3.name = "Hudular hajmi"
print(obj3)

Andijon                            4200
Buxoro                            39400
Farg'ona                           6800
Jizzax                            20500
Xorazm                             6300
Namangan                           7900
Navoiy                           110800
Qashqadaryo                       28400
Qoraqalpog'iston Respublikasi    160000
Samarqand                         16400
Sirdaryo                           5100
Surxondaryo                       20800
Toshkent                          15300
Name: Hudular hajmi, dtype: int64

### **13-mashq.** Yuqoridagi `Series` obyektidan hududi eng katta va eng kichik elementlarni chiqaring

In [250]:
# Javobni shuyerga yozing
a, b = obj3.argmax(), obj3.argmin()
print('Eng katta hudud:', obj3.index[a] )
print('Eng kichik hudud:', obj3.index[b])

Eng katta hudud: Qoraqalpog'iston Respublikasi
Eng kichik hudud: Andijon

In [251]:
print(f"Eng katta hudud: {obj3.idxmax()}")
print(f"Eng kichik hudud: {obj3.idxmin()}")

Eng katta hudud: Qoraqalpog'iston Respublikasi
Eng kichik hudud: Andijon

In [252]:
#@title To'g'ri javob
print(f"Eng katta hudud: {obj3.idxmax()}")
print(f"Eng kichik hudud: {obj3.idxmin()}")

Eng katta hudud: Qoraqalpog'iston Respublikasi
Eng kichik hudud: Andijon

In [253]:
obj2

Fargʻona                         1899000
Toshkent                         1384700
Samarqand                        2597000
Buxoro                            910500
Surxondaryo                      1200000
Qashqadaryo                      1862000
Xorazm                            767500
Namangan                         2029000
Andijon                          1200000
Jizzax                           2322000
Sirdaryo                          648100
Navoiy                           1676000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64

### **14-mashq.** Yuqoridagi eng katta va eng kichik hududlar aholisi sonini chiqaring

In [254]:
# Javobni shuyerga yozing
print(f"{obj3.idxmax()} aholisi {obj2[obj3.idxmax()]}")
print(f"{obj3.idxmin()} aholisi {obj2[obj3.idxmin()]}")

Qoraqalpog'iston Respublikasi aholisi 4450000
Andijon aholisi 1200000

In [255]:
#@title To'g'ri javob
print(f"{obj3.idxmax()} aholisi {obj2[obj3.idxmax()]}")
print(f"{obj3.idxmin()} aholisi {obj2[obj3.idxmin()]}")

Qoraqalpog'iston Respublikasi aholisi 4450000
Andijon aholisi 1200000

### **15-mashq**. Yuqoridagi hudulardan O'zbekiston Respublikasi hududini hisoblang

In [256]:
# Javobni shuyerga yozing
uz_hudud = obj3.sum()
uz_hudud

np.int64(441900)

In [257]:
#@title To'g'ri javob
sum(obj3)

441900

### **16-mashq.** Aholisi eng ko'p va eng kam hududlarning hajmini va aholi sonini chiqaring

In [258]:
# Javobni shuyerga yozing
print(f"{obj2.idxmax()} hududi {obj3[obj2.idxmax()]}kv.km, aholisi {obj2.max()}")
print(f"{obj2.idxmin()} hududi {obj3[obj2.idxmin()]}kv.km, aholisi {obj2.min()}")

Qoraqalpog'iston Respublikasi hududi 160000kv.km, aholisi 4450000
Sirdaryo hududi 5100kv.km, aholisi 648100

In [259]:
#@title To'g'ri javob
print(f"{obj2.idxmax()} hududi {obj3[obj2.idxmax()]}kv.km, aholisi {obj2[obj2.idxmax()]}")
print(f"{obj2.idxmin()} hududi {obj3[obj2.idxmin()]}kv.km, aholisi {obj2[obj2.idxmin()]}")

Qoraqalpog'iston Respublikasi hududi 160000kv.km, aholisi 4450000
Sirdaryo hududi 5100kv.km, aholisi 648100

### **17-mashq.** Yuqoridagi ikki obyektdan foydalangan holda O'zbekiston respublikasi tarkibidagi hududlarni avval aholi soni bo'yicha, keyin esa hajmi bo'yicha tartiblab chiqaring

In [265]:
# Javobni shuyerga yozing
print("Hududlar hajmi bo'yicha tartiblash")
obj3.sort_values()

Hududlar hajmi bo'yicha tartiblash

Andijon                            4200
Sirdaryo                           5100
Xorazm                             6300
Farg'ona                           6800
Namangan                           7900
Toshkent                          15300
Samarqand                         16400
Jizzax                            20500
Surxondaryo                       20800
Qashqadaryo                       28400
Buxoro                            39400
Navoiy                           110800
Qoraqalpog'iston Respublikasi    160000
Name: Hudular hajmi, dtype: int64

In [262]:
#@title To'g'ri javob
print("Hududlar hajmi bo'yicha tartiblash")
obj3.sort_values()

Hududlar hajmi bo'yicha tartiblash

Andijon                            4200
Sirdaryo                           5100
Xorazm                             6300
Farg'ona                           6800
Namangan                           7900
Toshkent                          15300
Samarqand                         16400
Jizzax                            20500
Surxondaryo                       20800
Qashqadaryo                       28400
Buxoro                            39400
Navoiy                           110800
Qoraqalpog'iston Respublikasi    160000
Name: Hudular hajmi, dtype: int64

In [267]:
print("Aholi soni bo'yicha tartiblash")
obj2.sort_values()

Aholi soni bo'yicha tartiblash

Sirdaryo                          648100
Xorazm                            767500
Buxoro                            910500
Surxondaryo                      1200000
Andijon                          1200000
Toshkent                         1384700
Navoiy                           1676000
Qashqadaryo                      1862000
Fargʻona                         1899000
Namangan                         2029000
Jizzax                           2322000
Samarqand                        2597000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64

In [268]:
#@title To'g'ri javob
print("Aholi soni bo'yicha tartiblash")
obj2.sort_values()

Aholi soni bo'yicha tartiblash

Sirdaryo                          648100
Xorazm                            767500
Buxoro                            910500
Surxondaryo                      1200000
Andijon                          1200000
Toshkent                         1384700
Navoiy                           1676000
Qashqadaryo                      1862000
Fargʻona                         1899000
Namangan                         2029000
Jizzax                           2322000
Samarqand                        2597000
Qoraqalpog'iston Respublikasi    4450000
dtype: int64