![Imgur](https://i.imgur.com/h4PPC71.png)

#Data Sayns va Sunʼiy Intellekt Praktikum

#9.32. Pandas kutubxonasi boʻyicha amaliy vazifa.

Yengillik yaratish maqsadida topshiriqlarni `📌Mavzulashtirilgan`

## `📌Pandas kutubxonasini yuklash`

**1.** Pandas kutubxonasini `pd` nomi ostida yuklang va uni chop eting.

In [1]:
import pandas as pd

**2.** Versiya va konfiguratsiyani tekshiring.

In [2]:
print(pd.__version__)
pd.get_option("display.max_rows")

2.2.2

60

**3.** Pandas kutubxonasida mavjud boʻlgan barcha versiya maʼlumotlarini chop eting.

In [3]:
pd.show_versions()

INSTALLED VERSIONS
------------------
commit                : d9cdd2ee5a58015ef6f4d15c7226110c9aab8140
python                : 3.12.13.final.0
python-bits           : 64
OS                    : Linux
OS-release            : 6.6.113+
Version               : #1 SMP Mon Feb  2 12:27:57 UTC 2026
machine               : x86_64
processor             : x86_64
byteorder             : little
LC_ALL                : en_US.UTF-8
LANG                  : en_US.UTF-8
LOCALE                : en_US.UTF-8

pandas                : 2.2.2
numpy                 : 2.0.2
pytz                  : 2025.2
dateutil              : 2.9.0.post0
setuptools            : 75.2.0
pip                   : 24.1.2
Cython                : 3.0.12
pytest                : 8.4.2
hypothesis            : None
sphinx                : 8.2.3
blosc                 : None
feather               : None
xlsxwriter            : None
lxml.etree            : 6.0.2
html5lib              : 1.1
pymysql               : None
psycopg2              : 2.9.11
jinja2                : 3.1.6
IPython               : 7.34.0
pandas_datareader     : 0.10.0
adbc-driver-postgresql: None
adbc-driver-sqlite    : None
bs4                   : 4.13.5
bottleneck            : 1.4.2
dataframe-api-compat  : None
fastparquet           : None
fsspec                : 2025.3.0
gcsfs                 : 2025.3.0
matplotlib            : 3.10.0
numba                 : 0.60.0
numexpr               : 2.14.1
odfpy                 : None
openpyxl              : 3.1.5
pandas_gbq            : 0.30.0
pyarrow               : 18.1.0
pyreadstat            : None
python-calamine       : None
pyxlsb                : None
s3fs                  : None
scipy                 : 1.16.3
sqlalchemy            : 2.0.48
tables                : 3.10.2
tabulate              : 0.9.0
xarray                : 2025.12.0
xlrd                  : 2.0.2
zstandard             : 0.25.0
tzdata                : 2025.3
qtpy                  : None
pyqt5                 : None

## `📌DataFrame: Asoslar`

DataFramesʼda maʼlumotlarni tanlash (selecting), saralash (sorting), qoʻshish (adding) va yigʻish (aggregating) uchun bir nechta asosiy mashqlar.

💡Eslatma: NumPy kutubxonasini import qilishni unutmang.
``` python
import numpy as np
```

Quyidagi Python lugʻati (dictionary) `data` va Python roʻyxati (list) `labels` ni koʻrib chiqing.


``` python
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

**4.** Ushbu `lugʻat` (dictionary) yordamida `data` dan `labels` indeksiga ega DataFrame yarating.

In [4]:
import numpy as np

data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(data, index = labels)
df.iloc[0]

animal      cat
age         2.5
visits        1
priority    yes
Name: a, dtype: object

**5.** Ushbu DataFrame va uning maʼlumotlari haqidagi asosiy maʼlumotlarning qisqacha mazmunini koʻrsating.

`💡Ishora:` DataFrameʼda chaqirilishi mumkin boʻlgan yagona usul mavjud.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   animal    10 non-null     object
 1   age       8 non-null      float64
 2   visits    10 non-null     int64
 3   priority  10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

**6.** DataFrame `df` dastlabki 3 qatorini qaytaring.

In [6]:
df.head(3)

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

In [7]:
df[0:3] #or df.iloc[0:3]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no

**7.** DataFrame `df`ʼdan faqat `animal` va `age` ustunlarini tanlang.

In [8]:
df.reindex(columns = ['animal','age'])

  animal  age
a    cat  2.5
b    cat  3.0
c  snake  0.5
d    dog  NaN
e    dog  5.0
f    cat  2.0
g  snake  4.5
h    cat  NaN
i    dog  7.0
j    dog  3.0

**8.** `[3, 4, 8]` va `['animal', 'age']` qatorlaridagi maʼlumotlarni tanlang.

In [9]:
df.reindex(columns = ['animal', 'age']).iloc[[3, 4, 8]]

  animal  age
d    dog  NaN
e    dog  5.0
i    dog  7.0

**9.** Faqat `visits` soni 3 tadan koʻp boʻlgan qatorlarni tanlang.

In [10]:
df[df.visits>3]

Empty DataFrame
Columns: [animal, age, visits, priority]
Index: []

10. Yosh yoʻqolgan qatorlarni tanlang, yaʼni `NaN`.

In [11]:
filtr = df['age'].isna()
df[filtr]

  animal  age  visits priority
d    dog  NaN       3      yes
h    cat  NaN       1      yes

**11.** `animal` qatoridagi `cat` va `age` qatoridagi `3` dan kichik boʻlgan umumiy qatorlarni tanlang.

In [12]:
df[(df.animal == 'cat') & (df.age < 3)]

  animal  age  visits priority
a    cat  2.5       1      yes
f    cat  2.0       3       no

**12.** `age` 2 va 4 (shu jumladan) orasidagi qatorlarni tanlang.

In [13]:
df[(df.age >= 2) & (df.age <= 4)]

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
f    cat  2.0       3       no
j    dog  3.0       1       no

**13.** `f` qatoridagi yoshni `1,5` ga oʻzgartiring.

In [14]:
df.at['f', 'age'] = 1.5 # yoki df.reindex(['f'], ['age']) = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [15]:
df.loc[['f'], ['age']] = 1.5
df

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  1.5       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

**14.** `df` yordamida `visits` qatorining yigʻindisini hisoblang.

In [16]:
df.visits.sum()

np.int64(19)

**15.** Har bir `animal` uchun oʻrtacha yoshni `df` da hisoblang.

In [17]:
df.groupby('animal')['age'].mean()

animal
cat      2.333333
dog      5.000000
snake    2.500000
Name: age, dtype: float64

In [18]:
cat = df[df.animal == 'cat']
dog = df[df.animal == 'dog']
snake = df[df.animal == 'snake']
agemean = [cat.age.mean(), dog.age.mean(), snake.age.mean()]
df_age = pd.Series(agemean, index = ['cat','dog','snake'])
df_age

cat      2.333333
dog      5.000000
snake    2.500000
dtype: float64

**16.** `df` yordamida har bir turdagi `animal` sonini hisoblang.

In [19]:
df.animal.value_counts()

animal
cat      4
dog      4
snake    2
Name: count, dtype: int64

**17.** `animal` ustunida, `snake` soʻzini `python` soʻziga oʻzgartiring.

In [20]:
df.animal = df.animal.replace({'snake':'python'})
df

   animal  age  visits priority
a     cat  2.5       1      yes
b     cat  3.0       3      yes
c  python  0.5       2       no
d     dog  NaN       3      yes
e     dog  5.0       2       no
f     cat  1.5       3       no
g  python  4.5       1       no
h     cat  NaN       1      yes
i     dog  7.0       2       no
j     dog  3.0       1       no

## `📌DataFrame: Murakkab`

### Darajasi murakkabroq vazifa: toʻgʻri javob olish uchun ikki yoki undan ortiq usullarni birlashtirish kerak boʻlishi mumkin

Oldingi boʻlim DataFrameʼning asosiy, ammo muhim operatsiyalari boʻyicha vazifalari jamlagan edi. Quyida maʼlumotlarni kesishingiz kerak boʻlgan mashqlar mavjud.

**18.** Sizda butun sonlardan iborat `A` ustunli DataFrame `df` mavjud. Misol uchun:
```python
df = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
```

Yuqoridagi qator bilan bir xil butun sonni oʻz ichiga olgan qator yarating.


💡Sizda quyidagi qiymatlarni oʻz ichiga olgan ustun paydo boʻlishi kerak:

```python
1, 2, 3, 4, 5, 6, 7
```

In [21]:
df1 = pd.DataFrame({'A': [1, 2, 2, 3, 4, 5, 5, 5, 6, 7, 7]})
df1.A.value_counts()

A
5    3
7    2
2    2
3    1
1    1
4    1
6    1
Name: count, dtype: int64

**19.** Raqamli qiymatlardan iborat DataFrame berildi.

```python
df = pd.DataFrame(np.random.random(size=(5, 3))) # float qiymatlarining 5x3 oʻlchovi
```

Qatordagi har bir elementdan satrning oʻrtacha qiymatini qanday ayirish mumkin?

In [22]:
df2 = pd.DataFrame(np.random.random(size=(5, 3)))
row_mean = df2.mean(axis=1)
result = df2 - row_mean
result.dropna(axis=1, inplace=True)
result

          0         1         2
0  0.179580 -0.214243 -0.101096
1  0.445640 -0.214601 -0.745773
2  0.451433  0.445101 -0.246040
3  0.012807 -0.211412 -0.609946
4  0.450774  0.214172 -0.485129

**20.** Sizda 10 ta haqiqiy raqamlar ustunidan iborat DataFrame mavjud:

``` python
df = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
```
Qaysi sonlar ustunining yigʻindisi eng kichik ekanini hisoblang. U ustunning yorligʻini qaytaring.

In [23]:
df3 = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df3.sum(axis=0)

a    1.195468
b    3.100494
c    2.231224
d    2.395782
e    1.466571
f    2.681834
g    2.594727
h    1.858743
i    2.186612
j    2.330852
dtype: float64

In [24]:
df3 = pd.DataFrame(np.random.random(size=(5, 10)), columns=list('abcdefghij'))
df3.sum(axis = 0).idxmin()

'c'

**21.** Quyida butun sonlardan iborat DataFrame `df` mavjud. Har bir satrga  5 ta yozuv `NaN` qiymatlari kiritilgan.

DataFrameʼning har bir qatori uchun uchinchi `NaN` qiymatini oʻz ichiga olgan ustunni toping.

Ustun yorliqlarini qaytarishingiz kerak: `e, c, d, h, d`

In [25]:
import numpy as np
nan = np.nan
data = [[0.04,  nan,  nan, 0.25,  nan, 0.43, 0.71, 0.51,  nan,  nan],
        [ nan,  nan,  nan, 0.04, 0.76,  nan,  nan, 0.67, 0.76, 0.16],
        [ nan,  nan, 0.5 ,  nan, 0.31, 0.4 ,  nan,  nan, 0.24, 0.01],
        [0.49,  nan,  nan, 0.62, 0.73, 0.26, 0.85,  nan,  nan,  nan],
        [ nan,  nan, 0.41,  nan, 0.05,  nan, 0.61,  nan, 0.48, 0.68]]

columns = list('abcdefghij')

df = pd.DataFrame(data, columns=columns)

# Javobni bu yerga yozing.
df
df_t = df.T
col1, col2, col3, col4, col5 = df_t[0], df_t[1], df_t[2], df_t[3], df_t[4]
for x in [col1.sort_values().index[-3], col2.sort_values().index[-3],\
          col3.sort_values().index[-3], col4.sort_values().index[-3],\
          col5.sort_values().index[-3]]:
          print(x, end = ", ")

e, c, d, h, d,

**22.** DataFrame `grps` guruhlari ustuniga va `vals` butun qiymatlari ustuniga ega:

```python
df = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
```
Har bir `grps` uchun uchta eng katta qiymatning yig‘indisini toping.

💡Javobni quyidagicha yakunlashingiz kerak:
```
grps
a    409
b    156
c    345
```

     'a   a  a b  b  c a a  b  c  c   c  b  b  c'
      12,345,3,1,45,14,4,52,54,23,235,21,57,3,87

In [26]:
# Javobni bu yerga yozing.
df4 = pd.DataFrame({'grps': list('aaabbcaabcccbbc'),
                   'vals': [12,345,3,1,45,14,4,52,54,23,235,21,57,3,87]})
df4.groupby('grps')['vals'].apply(lambda x: x.nlargest(3).sum())

grps
a    409
b    156
c    345
Name: vals, dtype: int64

**23.** Quyida tuzilgan DataFrame `df` ikkita butun son ustuniga ega `A` va `B`. `A` dagi qiymatlar 1 dan 100 gacha (shu jumladan).

`A` dagi har bir 10 ta ketma-ket butun sonlar guruhi uchun (ya’ni `(0, 10]`, `(10, 20]`, ...) 'B' ustunidagi mos qiymatlar yigʻindisini hisoblang.

Javob quyidagicha boʻlishi kerak:

```
A
(0, 10]      635
(10, 20]     360
(20, 30]     315
(30, 40]     306
(40, 50]     750
(50, 60]     284
(60, 70]     424
(70, 80]     526
(80, 90]     835
(90, 100]    852
```

In [27]:
df5 = pd.DataFrame(np.random.RandomState(8765).randint(1, 101, size=(100, 2)), columns = ["A", "B"])

# Javobni bu yerga yozing!
df5['A'] = pd.cut(df5.A, bins = [0,10,20,30,40,50,60,70,80,90,100])
df5.set_index(df5.A)
df5.groupby('A', observed = True).sum()

             B
A
(0, 10]    635
(10, 20]   360
(20, 30]   315
(30, 40]   306
(40, 50]   750
(50, 60]   284
(60, 70]   424
(70, 80]   526
(80, 90]   835
(90, 100]  852

In [28]:
df5.A.cat.categories

IntervalIndex([  (0, 10],  (10, 20],  (20, 30],  (30, 40],  (40, 50],
                (50, 60],  (60, 70],  (70, 80],  (80, 90], (90, 100]],
              dtype='interval[int64, right]')

In [29]:
display(df5.head())
df5.A.cat.codes

          A   B
0  (40, 50]  29
1  (70, 80]  22
2  (40, 50]  63
3  (30, 40]  43
4  (70, 80]  75

0     4
1     7
2     4
3     3
4     7
     ..
95    5
96    5
97    8
98    4
99    9
Length: 100, dtype: int8

In [30]:
df5.A.cat.rename_categories(['0-10','10-20','20-30','30-40','40-50','50-60','60-70','70-80','80-90','90-100'])

0      40-50
1      70-80
2      40-50
3      30-40
4      70-80
       ...
95     50-60
96     50-60
97     80-90
98     40-50
99    90-100
Name: A, Length: 100, dtype: category
Categories (10, object): ['0-10' < '10-20' < '20-30' < '30-40' ... '60-70' < '70-80' < '80-90' <
                          '90-100']

In [31]:
df8 = pd.DataFrame({
    'name': ['Ali','Vali','Sami','Lola','Zara','Olim'],
    'score': [30, 45, 60, 70, 85, 90]
})
df8['range'] = pd.cut(df8.score, bins=[0,50,75,100],labels=['Low','Medium','High'])
df8['range'].cat.as_unordered()
df8

   name  score   range
0   Ali     30     Low
1  Vali     45     Low
2  Sami     60  Medium
3  Lola     70  Medium
4  Zara     85    High
5  Olim     90    High

**24.** 'X' butun son ustuni boʻlgan DataFrame:
```python
df = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
```

Har bir qiymat uchun farqni oldingi nolga qaytaring.

Sizda natija quyidagicha boʻlishi kerak:

```
[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]
```

Buni yangi `Y` ustuni deb nomlang.

In [32]:
#javobni bu yerga yozing!
df6 = pd.DataFrame({'X': [7, 2, 0, 3, 4, 2, 5, 0, 3, 4]})
ind = df6.X.to_numpy()
m = -1
Y =[]
n = 0
while n < 10:
  if ind[n] != 0:
      pass
  else:
       m = n
  Y.append(n - m)
  n = n+1
print(Y)

[1, 2, 0, 1, 2, 3, 4, 0, 1, 2]

##`📌Maʼlumotlarni tozalash`

Bu har doim sodir boʻladi: kimdir sizga notoʻgʻri tuzilgan satrlar, roʻyxatlar va yetishmayotgan maʼlumotlarni oʻz ichiga olgan maʼlumotlarni beradi. Tahlilni davom ettirish uchun uni qanday tartibga keltirasiz?

**25.** Quyidagi jumboqni tasavvur qilishi uchun ushbu misolni DataFrame sifatida oling:

```python
df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
```
Tartiblaganingizdan soʻng u quyidagi koʻrinishga ega boʻlishi kerak:

```
            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"
```

In [33]:
df7 = df = pd.DataFrame({'From_To': ['LoNDon_paris', 'MAdrid_miLAN', 'londON_StockhOlm',
                               'Budapest_PaRis', 'Brussels_londOn'],
              'FlightNumber': [10045, np.nan, 10065, np.nan, 10085],
              'RecentDelays': [[23, 47], [], [24, 43, 87], [13], [67, 32]],
                   'Airline': ['KLM(!)', '<Air France> (12)', '(British Airways. )',
                               '12. Air France', '"Swiss Air"']})
df7

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris       10045.0      [23, 47]               KLM(!)
1      MAdrid_miLAN           NaN            []    <Air France> (12)
2  londON_StockhOlm       10065.0  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis           NaN          [13]       12. Air France
4   Brussels_londOn       10085.0      [67, 32]          "Swiss Air"

**26.** **FlightNumber** ustunidagi baʼzi qiymatlar yoʻq. Ular `NaN` koʻrinishida yozilgan. Bu raqamlar har bir qatorda 10 ga koʻpayishi kerak, shuning uchun 10055 va 10075 ni qoʻyish kerak. Ushbu yetishmayotgan raqamlarni toʻldirish uchun `df` ni oʻzgartiring va ustunni butun son ustuniga aylantiring.

In [34]:
df7['FlightNumber'] = df7['FlightNumber'].interpolate()
df7['FlightNumber'] = df7['FlightNumber'].astype(dtype = 'int64')
df7

            From_To  FlightNumber  RecentDelays              Airline
0      LoNDon_paris         10045      [23, 47]               KLM(!)
1      MAdrid_miLAN         10055            []    <Air France> (12)
2  londON_StockhOlm         10065  [24, 43, 87]  (British Airways. )
3    Budapest_PaRis         10075          [13]       12. Air France
4   Brussels_londOn         10085      [67, 32]          "Swiss Air"

**27.** **From\_To** ustunini ikkita alohida ustun koʻrinishida yozing.                                          

Toʻgʻri qiymatlarga ega `temp` deb nomlangan yangi Temporary DataFrame berish uchun har bir satrni pastki chiziq chegarasiga ajrating.                                                                     Ushbu Temporary DataFrame ustunlarini `From` va `To` deb nomlang.

In [35]:
fr = df7['From_To'].str.split("_").str[0].values
to = df7['From_To'].str.split("_").str[1].values
data = {'From': fr,
        "To" : to}
temp = pd.DataFrame(data)
temp

       From         To
0    LoNDon      paris
1    MAdrid      miLAN
2    londON  StockhOlm
3  Budapest      PaRis
4  Brussels     londOn

**28.** Temporary DataFrame `temp` da shahar nomlari betartib yozilgan.
Satrlarning faqat birinchi harfi katta yozilishi kerak.
                                                                         (Masalan, "londON" "London" boʻlishi kerak.)

In [36]:
temp.From = temp['From'].str.capitalize()
temp.To = temp['To'].str.capitalize()
temp

       From         To
0    London      Paris
1    Madrid      Milan
2    London  Stockholm
3  Budapest      Paris
4  Brussels     London

**29**. `Airline` ustunida aviakompaniya nomlari atrofida qoʻshimcha tinish belgilari va boshqa belgilar paydo boʻlganini koʻrishingiz mumkin. Faqat aviakompaniya nomini qoldiring. Masalan, ''(British Airways. )'' `British Airways` koʻrinishida yozilishi kerak.

In [37]:
df7['Airline'] = df7['Airline'].str.replace(r'[^a-zA-Z\s]', '', regex=True).str.strip()
df7

            From_To  FlightNumber  RecentDelays          Airline
0      LoNDon_paris         10045      [23, 47]              KLM
1      MAdrid_miLAN         10055            []       Air France
2  londON_StockhOlm         10065  [24, 43, 87]  British Airways
3    Budapest_PaRis         10075          [13]       Air France
4   Brussels_londOn         10085      [67, 32]        Swiss Air

**30.** `df` dan **From_To** ustunini oʻchiring va Temporary DataFrame `temp` ustunini qoʻshing.

In [38]:
df7.drop('From_To', axis = 1, inplace = True)
df7 = pd.concat([df7,temp],axis =1)

In [39]:
df7

   FlightNumber  RecentDelays          Airline      From         To
0         10045      [23, 47]              KLM    London      Paris
1         10055            []       Air France    Madrid      Milan
2         10065  [24, 43, 87]  British Airways    London  Stockholm
3         10075          [13]       Air France  Budapest      Paris
4         10085      [67, 32]        Swiss Air  Brussels     London

**31**. `RecentDelays` ustunida qiymatlar DataFrameʼga roʻyxat sifatida kiritilgan. Vazifangiz birinchi, har bir ikkinchi qiymatni oʻz ustunida va qolgan qiymatlar ham ustunga mos holda chop etish. Agar N-chi qiymat boʻlmasa, qiymat `NaN` deb nomlanishi kerak.

Roʻyxatlar qatorini `delays` nomli DataFrame ichiga kengaytiring, `delay_1`, `delay_2` va qolgan ustunlarni ham nomlarini oʻzgartiring va `df` dagi keraksiz `RecentDelays` ustunini `delays` bilan almashtiring.

Natija quyidagi koʻrinishda boʻlishi kerak:
```
   FlightNumber          Airline      From         To  delay_1  delay_2  delay_3
0         10045              KLM    London      Paris     23.0     47.0      NaN
1         10055       Air France    Madrid      Milan      NaN      NaN      NaN
2         10065  British Airways    London  Stockholm     24.0     43.0     87.0
3         10075       Air France  Budapest      Paris     13.0      NaN      NaN
4         10085        Swiss Air  Brussels     London     67.0     32.0      NaN
```

In [40]:
delays = pd.DataFrame(df7["RecentDelays"].tolist())
delays = delays.add_prefix("delay_")
delays.columns = [f"delay_{i+1}" for i in range(delays.shape[1])]
df7 = df7.drop("RecentDelays", axis=1).join(delays)
df7

,FlightNumber,Airline,From,To,delay_1,delay_2,delay_3
0,10045,KLM,London,Paris,23.0,47.0,NaN
1,10055,Air France,Madrid,Milan,NaN,NaN,NaN
2,10065,British Airways,London,Stockholm,24.0,43.0,87.0
3,10075,Air France,Budapest,Paris,13.0,NaN,NaN
4,10085,Swiss Air,Brussels,London,67.0,32.0,NaN

##`📌Minesweeper`


### Minesweeper tarmogʻida xavfsiz kvadratlar uchun raqamlar yaratamiz.

💡 Agar siz Windowsʼning avvalgi versiyalaridan foydalangan boʻlsangiz, Minesweeper bilan tanishsiz:
- https://en.wikipedia.org/wiki/Minesweeper_(video_game)

Agar siz oʻyin bilan tanish boʻlmasangiz, kvadratchalar toʻplamini tasavvur qiling: bu kvadratlarning baʼzilari mineʼni yashiradi. Agar siz mineʼni bossangiz, darhol yoʻqotasiz. Agar siz xavfsiz kvadratni bossangiz, darhol qoʻshni boʻlgan kvadratchalarda qancha mine borligini koʻrsatadigan raqamni koʻrasiz. Oʻyinning maqsadi toʻrdagi mine boʻlmagan barcha kvadratlarni ochishdir.

Ushbu boʻlimda Minesweeper oʻyini uchun kerakli maʼlumotlarni oʻz ichiga olgan DataFrame yaratamiz: kvadratlarning koordinatalari, kvadratda mine bormi va qoʻshni kvadratlarda topilgan mineʼlar sonini aniqlaymiz.

**32**. Tasavvur qiling, biz Minesweeper oʻyinini 5 dan 4 gacha boʻlgan panjarada oʻynayapmiz, yaʼni.
```
X = 5
Y = 4
```
Boshlash uchun ikkita ustunli DataFrame `df` yarating, bu tarmoq uchun har bir koordinatani oʻz ichiga olgan `'x'` va `'y'`. Yaʼni DataFrame ishga tushishi kerak:
```
    x y
0 0 0
1 0 1
2 0 2
```

In [52]:
from itertools import product

x = range(5)   # 0,1,2,3,4
y = range(4)   # 0,1,2,3

df = pd.DataFrame(list(product(x, y)), columns=["x", "y"])
df.head()

   x  y
0  0  0
1  0  1
2  0  2
3  0  3
4  1  0

**33**. Ushbu DataFrame `df` uchun yangi nol (safe) va birliklar (mine) ustunini yarating. Har bir joyda mine sodir boʻlish ehtimoli 0,4 boʻlishi kerak.

In [54]:
df['mine'] = np.random.choice([0, 1], size=len(df), p=[0.6, 0.4])
df['safe'] = 1- df.mine
df.head()

   x  y  mine  safe
0  0  0     0     1
1  0  1     1     0
2  0  2     1     0
3  0  3     1     0
4  1  0     0     1

 **34**. Endi ushbu DataFrame uchun `adjacent` nomli yangi ustun yarating. Ushbu ustunda tarmoqdagi qoʻshni kvadratlarda topilgan mineʼlar soni boʻlishi kerak.

(Masalan, `(0, 0)` koordinatasi uchun yozuv boʻlgan birinchi qator uchun `(0, 1)`, `(1, 0)` va `(1) koordinatalarida qancha mine borligini hisoblang. , 1)`.)

In [57]:
def count_adjacent(row, df):
    x, y = row["x"], row["y"]

    neighbors = df[
        (df["x"].between(x-1, x+1)) &
        (df["y"].between(y-1, y+1)) &
        ~((df["x"] == x) & (df["y"] == y))
    ]

    return neighbors["mine"].sum()
df["adjacent"] = df.apply(lambda row: count_adjacent(row, df), axis=1)
df.head()

   x  y  mine  safe  adjacent
0  0  0     0     1         2
1  0  1     1     0         2
2  0  2     1     0         4
3  0  3     1     0         2
4  1  0     0     1         3

**35**. Mineʼni oʻz ichiga olgan DataFrame qatorlari uchun `adjacent` ustunidagi qiymatni `NaN` ga oʻzgartiring.

In [58]:
df.loc[df["mine"] == 1, "adjacent"] = np.nan

**36**. DataFrame-ni `adjacent` mineʼlar sonining panjarasiga aylantiring: ustunlar `x` koordinatasi, qatorlar `y` koordinatasi.

In [60]:
grid = df.pivot(index="y", columns="x", values="adjacent")
grid

x    0    1    2    3    4
y
0  2.0  3.0  NaN  2.0  1.0
1  NaN  NaN  4.0  NaN  2.0
2  NaN  6.0  6.0  NaN  3.0
3  NaN  NaN  NaN  NaN  2.0

##📌BONUS vazifa

Quyida sizga oquvchilarning test natijalari haqidagi DataFrame beriladi, yani `df_score` nomi ostida. Siz ushbu df Dataframedan `school_setting` ustuni boyicha guruhlab studentlarning har bir guruhdagi soni, posstest va protest test natijalarining ortacha qiymatini consulga chiqaring.

In [46]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("kwadwoofosu/predict-test-scores-of-students")

print("Path to dataset files:", path)

Downloading to /root/.cache/kagglehub/datasets/kwadwoofosu/predict-test-scores-of-students/1.archive...

100%|██████████| 21.0k/21.0k [00:00<00:00, 27.8MB/s]

Extracting files...
Path to dataset files: /root/.cache/kagglehub/datasets/kwadwoofosu/predict-test-scores-of-students/versions/1

In [47]:
import os

# The 'path' variable holds the directory where the dataset is downloaded.
# We need to find the actual CSV file inside this directory.

csv_files = [f for f in os.listdir(path) if f.endswith('.csv')]

if csv_files:
    # Assuming the first CSV file found is the one we want to load
    file_to_load = os.path.join(path, csv_files[0])
    df_score = pd.read_csv(file_to_load)
    print(f"Successfully loaded '{csv_files[0]}' into df_score.")
    display(df_score.head())
else:
    print(f"No CSV files found in the directory: {path}")
    print("Please check the dataset contents or specify the exact file name if you know it.")

Successfully loaded 'test_scores.csv' into df_score.

,school,school_setting,school_type,classroom,teaching_method,n_student,student_id,gender,lunch,pretest,posttest
0,ANKYI,Urban,Non-public,6OL,Standard,20.0,2FHT3,Female,Does not qualify,62.0,72.0
1,ANKYI,Urban,Non-public,6OL,Standard,20.0,3JIVH,Female,Does not qualify,66.0,79.0
2,ANKYI,Urban,Non-public,6OL,Standard,20.0,3XOWE,Male,Does not qualify,64.0,76.0
3,ANKYI,Urban,Non-public,6OL,Standard,20.0,556O0,Female,Does not qualify,61.0,77.0
4,ANKYI,Urban,Non-public,6OL,Standard,20.0,74LOE,Male,Does not qualify,64.0,76.0

In [48]:
df_score.head()

,school,school_setting,school_type,classroom,teaching_method,n_student,student_id,gender,lunch,pretest,posttest
0,ANKYI,Urban,Non-public,6OL,Standard,20.0,2FHT3,Female,Does not qualify,62.0,72.0
1,ANKYI,Urban,Non-public,6OL,Standard,20.0,3JIVH,Female,Does not qualify,66.0,79.0
2,ANKYI,Urban,Non-public,6OL,Standard,20.0,3XOWE,Male,Does not qualify,64.0,76.0
3,ANKYI,Urban,Non-public,6OL,Standard,20.0,556O0,Female,Does not qualify,61.0,77.0
4,ANKYI,Urban,Non-public,6OL,Standard,20.0,74LOE,Male,Does not qualify,64.0,76.0

In [49]:
df_score.groupby('school_setting').agg({'n_student' : 'sum', 'pretest':'mean', 'posttest':'mean'})

                n_student    pretest   posttest
school_setting
Rural             10208.0  51.490196  64.050980
Suburban          15547.0  63.841004  76.037657
Urban             22870.0  49.875276  61.748344