![Imgur](https://i.imgur.com/h4PPC71.png)
#11-modul. Maʼlumotlarga ishlov berish. Maʼlumotlarni tayyorlash
# 11.28. Modul boʻyicha yakuniy amaliy vazifa

**Bu vazifalarni bajargach, maʼlumotlarni yuklash, tozalash, oʻzgartirish, matnlarni normalizatsiya qilish, qiymatlarni tekshirish, guruhlash va tahlil qilish kabi maʼlumotlarga ishlov berish (data processing) koʻnikmalarini egallaysiz.**

#**Umumiy maʼlumotlar bilan ishlash**

#Dataset haqida qisqacha maʼlumot
Restoran savdosi boʻyicha maʼlumotlar toʻplami 17 534 tranzaksiya uchun maʼlumotlarni oʻz ichiga oladi. Maʼlumotlar yetishmayotgan yoki baʼzilari toʻliq kiritilmagan boʻlishi mumkin. Maʼlumotlar toʻplamida asosiy taomlar, shirinliklar, ichimliklar kabi bir nechta toifadagi savdo tafsilotlari mavjud.


 0.   **Unnamed 0** – indekslarni;
 1.   **Order ID** – buyurtma IDʼsini;
 2.   **Customer ID** – mijoz IDʼsini;
 3.   **Category** – mahsulotlar kategoriyasini;
 4.   **Item** – mahsulot nomini;
 5.   **Price** – mahsulotning narxini;
 6.   **Quantity** – qancha mahsulot sotilgani miqdorini;
 7.   **Order Total** – umumiy narx qancha ekanini;
 8.   **Order Date** – buyurtma berilgan sanani (vaqt);
 9.   **Payment Method** – toʻlov usuli turini saqlaydi.

#1) Quyida berilgan datasetni yuklab olib, ustun nomlarini koʻring va ularni maʼno jihatdan tushunarli shaklga keltiring. `Unnamed: 0` ustunini tashlab yuboring!

In [1]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/alishermutalov/praktikum-datasets/refs/heads/praktikum/restaurant_sales.csv"
df = pd.read_csv(url)
df.head()

,Unnamed: 0,Order ID,Customer ID,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

In [2]:
#javobni shu yerda yozing
df.drop(['Unnamed: 0'], axis = 'columns', inplace=True)
df.rename(columns = {'Order ID':'order_id','Customer ID':'customer_id'}, inplace = True)
df.head()

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,NaN,-1.0,2.0,5.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#2) Maʼlumotlarning umumiy holatini (info(), describe()) tekshiring.

In [3]:
#javobni shu yerda yozing
print(df.info())
print(df.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   Category        17498 non-null  object
 3   Item            15776 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17104 non-null  float64
 6   Order Total     17104 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  16452 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB
None
              Price      Quantity   Order Total
count  17534.000000  17104.000000  17104.000000
mean       6.207312      3.014149     19.914494
std        4.993782      1.414598     18.732549
min       -1.000000      1.000000      1.000000
25%        3.000000      2.000000      7.500000
50%        5.000000      3.000000     15.000000
75%        7.000000      4.000000     25.000000
max       20.000000      5.000000    100.000000

#3) Har bir ustundagi boʻsh qiymatlarni aniqlang va ularni toʻldirish strategiyasini ishlab chiqing.

In [4]:
#javobni shu yerda yozing
df.isnull().sum()

order_id             0
customer_id          0
Category            36
Item              1758
Price                0
Quantity           430
Order Total        430
Order Date           0
Payment Method    1082
dtype: int64

In [5]:
df.Category.value_counts()
#df.dropna(subset = ['Category'], inplace = True)

Category
Main Dishes    3544
Starters       3517
Desserts       3493
Drinks         3479
Side Dishes    3465
Name: count, dtype: int64

In [6]:
df[df.Category.isnull()]

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
500,ORD_437474,CUST_008,NaN,ORANGE JUICE#,3.0,1.0,3.0,2022-02-16,Credit Card
1000,ORD_293154,CUST_038,NaN,ICE CREAM#,5.0,5.0,25.0,2023-03-08,Credit Card
1500,ORD_844041,CUST_013,NaN,SIDE SALAD#,3.0,4.0,12.0,2023-11-11,Cash
2000,ORD_596859,CUST_082,NaN,SALMON#,18.0,5.0,90.0,2023-10-12,Credit Card
2500,ORD_425000,CUST_047,NaN,STEAK#,20.0,2.0,40.0,2023-01-02,Digital Wallet
3000,ORD_528695,CUST_068,NaN,NaN,-1.0,NaN,NaN,2022-05-01,NaN
3500,ORD_135296,CUST_098,NaN,WATER#,1.0,4.0,4.0,2022-12-14,Digital Wallet
4000,ORD_817203,CUST_058,NaN,SWEET POTATO FRIES#,5.0,4.0,20.0,2023-09-25,Digital Wallet
4500,ORD_111816,CUST_067,NaN,ICED TEA#,2.5,4.0,10.0,2023-08-08,Cash
5000,ORD_519405,CUST_063,NaN,PASTA ALFREDO#,12.0,1.0,12.0,2022-12-05,Credit Card
5500,ORD_590414,CUST_060,NaN,ice cream#,5.0,1.0,5.0,2022-01-23,Cash
6000,ORD_471646,CUST_019,NaN,COCA COLA#,2.5,4.0,10.0,2023-07-24,Digital Wallet
6500,ORD_333952,CUST_051,NaN,GRILLED VEGETABLES#,5.0,1.0,5.0,2022-12-26,Credit Card
7000,ORD_829247,CUST_004,NaN,CHICKEN MELT#,8.0,4.0,32.0,2023-02-09,NaN
7500,ORD_223169,CUST_064,NaN,SIDE SALAD#,3.0,2.0,6.0,2023-09-05,Digital Wallet
8000,ORD_272421,CUST_024,NaN,GRILLED CHICKEN#,15.0,1.0,15.0,2023-05-22,Digital Wallet
8500,ORD_729483,CUST_007,NaN,LEMONADE#?,3.0,2.0,6.0,2022-11-27,Cash
9000,ORD_240230,CUST_094,NaN,WATER#,1.0,3.0,3.0,2022-12-13,Cash
9500,ORD_479884,CUST_046,NaN,GRILLED CHICKEN#,15.0,4.0,60.0,2022-06-05,Cash
10000,ORD_708967,CUST_004,NaN,COCA COLA#,2.5,1.0,2.5,2023-07-16,Cash
10500,ORD_402838,CUST_023,NaN,NaN,-1.0,NaN,NaN,2022-01-20,Cash
11000,ORD_917386,CUST_014,NaN,grilled vegetables#,5.0,2.0,10.0,2023-10-16,Credit Card
11500,ORD_458746,CUST_048,NaN,SALMON#,18.0,3.0,54.0,2023-05-29,Credit Card
12000,ORD_374401,CUST_006,NaN,BEEF CHILI#,7.0,2.0,14.0,2023-05-06,Digital Wallet
12500,ORD_321550,CUST_040,NaN,FRENCH FRIES#,4.0,4.0,16.0,2022-05-28,Cash
13000,ORD_709816,CUST_068,NaN,CHEESE FRIES#,5.0,4.0,20.0,2023-07-17,Cash
13500,ORD_400801,CUST_038,NaN,COCA COLA#,2.5,2.0,5.0,2023-11-25,Digital Wallet
14000,ORD_895987,CUST_055,NaN,BROWNIE#,6.0,3.0,18.0,2023-09-13,Digital Wallet
14500,ORD_436582,CUST_077,NaN,CHICKEN MELT#,8.0,5.0,40.0,2023-12-29,Credit Card
15000,ORD_536106,CUST_054,NaN,ORANGE JUICE#,3.0,1.0,3.0,2023-03-13,Digital Wallet
15500,ORD_810133,CUST_025,NaN,NaN,-1.0,NaN,NaN,2022-09-30,NaN
16000,ORD_838405,CUST_022,NaN,FRENCH FRIES#,4.0,5.0,20.0,2023-04-03,Credit Card
16500,ORD_780771,CUST_093,NaN,mashed potatoes#,4.0,4.0,16.0,2023-01-02,Digital Wallet
17000,ORD_666259,CUST_013,NaN,NaN,-1.0,5.0,25.0,2022-10-04,NaN
17500,ORD_230561,CUST_085,NaN,BEEF CHILI#,7.0,3.0,21.0,2023-03-27,Cash

In [7]:
print(int(df.Quantity.mean()))
int(df['Order Total'].mean())

3

19

In [8]:
df.fillna({'Quantity' : int(df.Quantity.mean())}, inplace = True)
df['Order Total'] = np.abs(df.Price*df.Quantity)
df.sample(10)

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
5674,ORD_161326,CUST_071,Starters,Beef Chili,7.0,3.0,21.0,2022-02-14,NaN
1358,ORD_338946,CUST_069,Drinks,Water (0.5),1.0,1.0,1.0,2023-02-21,Cash
605,ORD_839265,CUST_088,Desserts,cheesecake,7.0,1.0,7.0,2022-12-18,Digital Wallet
5429,ORD_430241,CUST_078,Drinks,Water (0.5),1.0,4.0,4.0,2023-11-30,Cash
13397,ORD_635551,CUST_061,Desserts,Chocolate Cake,6.0,5.0,30.0,2023-02-01,Credit Card
6951,ORD_701997,CUST_097,Side Dishes,NaN,3.0,4.0,12.0,2023-11-03,Cash
16857,ORD_992163,CUST_094,Starters,Sweet Potato Fries,5.0,2.0,10.0,2023-12-06,Credit Card
8623,ORD_597084,CUST_040,Drinks,Coca Cola,2.5,3.0,7.5,2023-12-12,Credit Card
14295,ORD_325686,CUST_042,Drinks,Lemonade,3.0,1.0,3.0,2022-10-01,Digital Wallet
12270,ORD_504225,CUST_078,Side Dishes,NaN,-1.0,4.0,4.0,2023-02-06,Digital Wallet

In [9]:
df['Payment Method'].value_counts()
df['Payment Method'] = df['Payment Method'].ffill()

In [10]:
df.isnull().sum()

order_id             0
customer_id          0
Category            36
Item              1758
Price                0
Quantity             0
Order Total          0
Order Date           0
Payment Method       0
dtype: int64

In [11]:
df.groupby(['Category','Price'])['Item'].count()

Category     Price
Desserts     -1.0        0
              4.0      449
              5.0      934
              6.0     1266
              7.0      485
Drinks       -1.0        0
              1.0      954
              2.5     1080
              3.0     1067
Main Dishes  -1.0        0
              12.0     997
              14.0     382
              15.0     820
              18.0     420
              20.0     573
Side Dishes  -1.0        0
              3.0      975
              4.0     1197
              5.0      949
Starters     -1.0        0
              4.0      895
              5.0     1155
              7.0      468
              8.0      440
              10.0     238
Name: Item, dtype: int64

In [12]:
df[(df.Price < 0) & (df.Category == "Drinks")] = df[(df.Price < 0) & (df.Category == "Drinks")].fillna({'Item':df[(df.Price == 1) & (df.Category == "Drinks")].iat[0,3]})

In [13]:
int(df[df.Category =='Drinks'].Price.mean())

2

In [14]:
df.columns[3]

'Item'

In [15]:
df[(df.Price < 0) & (df.Category == "Drinks")].head()

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
3,ORD_630508,CUST_075,Drinks,Water (0.5),-1.0,2.0,2.0,2022-08-09,Credit Card
112,ORD_289733,CUST_057,Drinks,Water (0.5),-1.0,5.0,5.0,2022-01-05,Digital Wallet
131,ORD_467157,CUST_099,Drinks,Water (0.5),-1.0,3.0,3.0,2023-11-30,Credit Card
288,ORD_594234,CUST_098,Drinks,Water (0.5),-1.0,3.0,3.0,2022-03-17,Credit Card
304,ORD_530791,CUST_038,Drinks,Water (0.5),-1.0,2.0,2.0,2023-06-12,Digital Wallet

In [16]:
lis = df.Category.unique()
x = lis.tolist()
x.remove('Drinks')
x

[nan, 'Side Dishes', 'Main Dishes', 'Desserts', 'Starters']

In [17]:
df[df.Price<0].Price.unique()

array([-1.])

In [18]:
for idx in x[1:]:
  df[(df.Price < 0) & (df.Category == idx)] = df[(df.Price < 0) & (df.Category == idx)].fillna({'Item' : df[(df.Price == int(df[df.Category == idx].Price.mean())) & (df.Category == idx)].iat[1, 3]})
  df.loc[
    (df.Price < 0) & (df.Category == idx),
    'Price'
] = int(df[df.Category == idx].Price.mean())

In [19]:
df[(df.Price < 0) & (df.Category == 'Side Dishes')].isnull().sum()

order_id          0
customer_id       0
Category          0
Item              0
Price             0
Quantity          0
Order Total       0
Order Date        0
Payment Method    0
dtype: int64

In [20]:
df.isnull().sum()

order_id            0
customer_id         0
Category           36
Item              886
Price               0
Quantity            0
Order Total         0
Order Date          0
Payment Method      0
dtype: int64

In [21]:
df[df.Category.notnull()]

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,Water (0.5),-1.0,2.0,2.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash
5,ORD_381680,CUST_031,Main Dishes,Salmon,18.0,5.0,90.0,2022-07-20,Digital Wallet
...,...,...,...,...,...,...,...,...,...
17529,ORD_320102,CUST_021,Drinks,Water (0.5),-1.0,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,NaN,7.0,4.0,28.0,2023-01-07,Digital Wallet

In [69]:
df.loc[df.Category.notnull(), 'Item'] = df[df.Category.notnull()].groupby(['Category', 'Price'])['Item'].transform(
        lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else x

)

In [23]:
df[df.Category.isnull()]

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
500,ORD_437474,CUST_008,NaN,ORANGE JUICE#,3.0,1.0,3.0,2022-02-16,Credit Card
1000,ORD_293154,CUST_038,NaN,ICE CREAM#,5.0,5.0,25.0,2023-03-08,Credit Card
1500,ORD_844041,CUST_013,NaN,SIDE SALAD#,3.0,4.0,12.0,2023-11-11,Cash
2000,ORD_596859,CUST_082,NaN,SALMON#,18.0,5.0,90.0,2023-10-12,Credit Card
2500,ORD_425000,CUST_047,NaN,STEAK#,20.0,2.0,40.0,2023-01-02,Digital Wallet
3000,ORD_528695,CUST_068,NaN,NaN,-1.0,3.0,3.0,2022-05-01,Credit Card
3500,ORD_135296,CUST_098,NaN,WATER#,1.0,4.0,4.0,2022-12-14,Digital Wallet
4000,ORD_817203,CUST_058,NaN,SWEET POTATO FRIES#,5.0,4.0,20.0,2023-09-25,Digital Wallet
4500,ORD_111816,CUST_067,NaN,ICED TEA#,2.5,4.0,10.0,2023-08-08,Cash
5000,ORD_519405,CUST_063,NaN,PASTA ALFREDO#,12.0,1.0,12.0,2022-12-05,Credit Card
5500,ORD_590414,CUST_060,NaN,ice cream#,5.0,1.0,5.0,2022-01-23,Cash
6000,ORD_471646,CUST_019,NaN,COCA COLA#,2.5,4.0,10.0,2023-07-24,Digital Wallet
6500,ORD_333952,CUST_051,NaN,GRILLED VEGETABLES#,5.0,1.0,5.0,2022-12-26,Credit Card
7000,ORD_829247,CUST_004,NaN,CHICKEN MELT#,8.0,4.0,32.0,2023-02-09,Digital Wallet
7500,ORD_223169,CUST_064,NaN,SIDE SALAD#,3.0,2.0,6.0,2023-09-05,Digital Wallet
8000,ORD_272421,CUST_024,NaN,GRILLED CHICKEN#,15.0,1.0,15.0,2023-05-22,Digital Wallet
8500,ORD_729483,CUST_007,NaN,LEMONADE#?,3.0,2.0,6.0,2022-11-27,Cash
9000,ORD_240230,CUST_094,NaN,WATER#,1.0,3.0,3.0,2022-12-13,Cash
9500,ORD_479884,CUST_046,NaN,GRILLED CHICKEN#,15.0,4.0,60.0,2022-06-05,Cash
10000,ORD_708967,CUST_004,NaN,COCA COLA#,2.5,1.0,2.5,2023-07-16,Cash
10500,ORD_402838,CUST_023,NaN,NaN,-1.0,3.0,3.0,2022-01-20,Cash
11000,ORD_917386,CUST_014,NaN,grilled vegetables#,5.0,2.0,10.0,2023-10-16,Credit Card
11500,ORD_458746,CUST_048,NaN,SALMON#,18.0,3.0,54.0,2023-05-29,Credit Card
12000,ORD_374401,CUST_006,NaN,BEEF CHILI#,7.0,2.0,14.0,2023-05-06,Digital Wallet
12500,ORD_321550,CUST_040,NaN,FRENCH FRIES#,4.0,4.0,16.0,2022-05-28,Cash
13000,ORD_709816,CUST_068,NaN,CHEESE FRIES#,5.0,4.0,20.0,2023-07-17,Cash
13500,ORD_400801,CUST_038,NaN,COCA COLA#,2.5,2.0,5.0,2023-11-25,Digital Wallet
14000,ORD_895987,CUST_055,NaN,BROWNIE#,6.0,3.0,18.0,2023-09-13,Digital Wallet
14500,ORD_436582,CUST_077,NaN,CHICKEN MELT#,8.0,5.0,40.0,2023-12-29,Credit Card
15000,ORD_536106,CUST_054,NaN,ORANGE JUICE#,3.0,1.0,3.0,2023-03-13,Digital Wallet
15500,ORD_810133,CUST_025,NaN,NaN,-1.0,3.0,3.0,2022-09-30,Cash
16000,ORD_838405,CUST_022,NaN,FRENCH FRIES#,4.0,5.0,20.0,2023-04-03,Credit Card
16500,ORD_780771,CUST_093,NaN,mashed potatoes#,4.0,4.0,16.0,2023-01-02,Digital Wallet
17000,ORD_666259,CUST_013,NaN,NaN,-1.0,5.0,5.0,2022-10-04,Digital Wallet
17500,ORD_230561,CUST_085,NaN,BEEF CHILI#,7.0,3.0,21.0,2023-03-27,Cash

In [24]:
df.isnull().sum()

order_id           0
customer_id        0
Category          36
Item               4
Price              0
Quantity           0
Order Total        0
Order Date         0
Payment Method     0
dtype: int64

In [25]:
df.sample(10)

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
11591,ORD_283556,CUST_016,Side Dishes,Garlic Bread,4.0,3.0,12.0,2022-04-18,Cash
16662,ORD_956680,CUST_086,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-08-12,Digital Wallet
2184,ORD_169284,CUST_083,Side Dishes,Mashed Potatoes,4.0,5.0,20.0,2022-03-09,Digital Wallet
300,ORD_625602,CUST_055,Main Dishes,GRILLED CHICKEN#,15.0,3.0,45.0,2022-05-08,Cash
10270,ORD_754330,CUST_024,Drinks,Water (0.5),1.0,2.0,2.0,2022-08-04,Digital Wallet
87,ORD_772436,CUST_031,Drinks,Coca Cola,2.5,4.0,10.0,2023-01-28,Digital Wallet
12343,ORD_528621,CUST_019,Starters,Sweet Potato Fries,5.0,2.0,10.0,2022-09-09,Cash
17491,ORD_820372,CUST_061,Side Dishes,Onion Rings,5.0,4.0,20.0,2023-12-14,Credit Card
1773,ORD_444646,CUST_087,Side Dishes,Side Salad,3.0,3.0,3.0,2023-03-11,Digital Wallet
4388,ORD_273757,CUST_039,Drinks,Iced Tea,2.5,3.0,7.5,2022-02-25,Cash

#4) Har bir ustundagi takroriy qiymatlarni toping va ularga qanday oʻzgartirish kiritish kerakligini hal qiling.

In [26]:
for x in ['order_id','customer_id','Order Date']:
   print(x, df[x].duplicated().sum())

order_id 0
customer_id 17434
Order Date 16804

In [27]:
df.groupby('customer_id').count()

,order_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
customer_id,,,,,,,,
CUST_001,178,178,178,178,178,178,178,178
CUST_002,177,177,177,177,177,177,177,177
CUST_003,163,163,163,163,163,163,163,163
CUST_004,174,172,174,174,174,174,174,174
CUST_005,158,158,158,158,158,158,158,158
...,...,...,...,...,...,...,...,...
CUST_096,194,194,194,194,194,194,194,194
CUST_097,184,184,184,184,184,184,184,184
CUST_098,180,179,180,180,180,180,180,180
CUST_099,163,163,163,163,163,163,163,163
CUST_100,200,200,200,200,200,200,200,200

In [28]:
df.duplicated().sum()

np.int64(0)

In [29]:
#javobni shu yerda yozing
df['order_id'].duplicated().sum()

np.int64(0)

In [30]:
df['Order Date'].duplicated().sum()

np.int64(16804)

In [31]:
df.head()

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,side salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,Water (0.5),-1.0,2.0,2.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

### Men Customer Id ustunida 100 ta mijozning idlari takrorlangan ekan. bularni takrorlanmas qilish yolini pastga yozib qoydim. Lekin bu kodni ishga tushirmadim, chunki bitta mijoz bir nechta mahsulotni sotib olgan bolishis mumkin. Shuningdek, Order Date ustunida ham takroriy qiymatlar bo'lgani yaxshi, sababi bir kunda bir qancha mahsulotlar sotilishi mumkin.

In [32]:
#df = df.reset_index()
#df.drop(columns = 'index')
#df.head()
#for n in range(len(df)):
#    df['Customer ID'].iat[n] = f'CUST_{n+1}'

In [33]:
df['customer_id'].duplicated().sum()

np.int64(17434)

In [34]:
df.tail()

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
17529,ORD_320102,CUST_021,Drinks,Water (0.5),-1.0,4.0,4.0,2023-12-23,Cash
17530,ORD_974128,CUST_069,Desserts,Ice Cream,5.0,3.0,15.0,2023-12-18,Cash
17531,ORD_108324,CUST_050,Desserts,Ice Cream,5.0,4.0,20.0,2022-05-20,Digital Wallet
17532,ORD_612647,CUST_073,Side Dishes,Mashed Potatoes,4.0,2.0,8.0,2022-01-27,Digital Wallet
17533,ORD_680707,CUST_006,Desserts,Cheesecake,7.0,4.0,28.0,2023-01-07,Digital Wallet

#5) Maʼlumotlar toʻplamidagi noto‘g‘ri maʼlumotlar (masalan, son turishi kerak bo‘lgan ustunda matn bo‘lsa) mavjudligini tekshiring va to‘g‘rilang.

In [35]:
#javobni shu yerda yozing
print(df.Price.unique())
print(df.Quantity.unique())
print(df['Order Total'].unique())
print(df['Order Date'].str.len().value_counts())

[ 3.   4.  15.  -1.  12.  18.   6.  14.   5.   2.5  7.   8.   1.  10.
 20. ]
[1. 3. 4. 2. 5.]
[  3.   12.   60.    2.   48.   90.   20.   45.   70.   18.    6.   56.
  72.   30.    2.5  42.   10.    5.   15.   24.   35.   25.   32.    9.
   8.   16.    7.   12.5  36.   75.    4.   40.   14.    1.    7.5  28.
  50.   80.   21.  100.   54. ]
Order Date
10    17534
Name: count, dtype: int64

#6) Maʼlumotlar toʻplamidagi **katta/kichik harf** muammolari boʻlgan joylarni toping va bir xil formatga keltiring.

In [36]:
#javobni shu yerda yozing
lis2 = ['Category', 'Item', 'Payment Method']
for idx in lis2:
  df[idx] = df[idx].str.title()

In [37]:
df.sample(10)

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
15815,ORD_520528,CUST_015,Drinks,Water (0.5),1.0,4.0,4.0,2022-04-20,Credit Card
12582,ORD_632957,CUST_056,Side Dishes,Garlic Bread,4.0,2.0,8.0,2022-01-19,Digital Wallet
16582,ORD_359469,CUST_094,Side Dishes,Mashed Potatoes,4.0,1.0,4.0,2022-05-14,Cash
12945,ORD_126644,CUST_040,Side Dishes,Grilled Vegetables,5.0,2.0,10.0,2023-03-21,Credit Card
11636,ORD_870425,CUST_086,Desserts,Ice Cream,5.0,1.0,5.0,2023-10-24,Cash
13058,ORD_289529,CUST_048,Side Dishes,Mashed Potatoes,4.0,4.0,16.0,2022-11-18,Credit Card
5221,ORD_821907,CUST_068,Desserts,Ice Cream,5.0,4.0,20.0,2022-03-18,Digital Wallet
8788,ORD_262026,CUST_060,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2022-10-26,Credit Card
11841,ORD_515191,CUST_016,Starters,Cheese Fries,5.0,2.0,10.0,2022-05-05,Digital Wallet
7876,ORD_325943,CUST_038,Starters,Beef Chili,7.0,2.0,14.0,2022-07-09,Credit Card

#7) Maʼlumotlar turini oʻzgartirish.
 * Ustunlarning maʼlumot turlarini tekshiring. Notoʻgʻri turlarga ega boʻlgan ustunlarni toʻgʻri formatga oʻtkazing.
 * `order_date` yoki unga oʻxshash ustunni datetime formatiga oʻtkazing.

In [38]:
#javobni shu yerda yozing
df.info()
df['Order Date'] = pd.to_datetime(df['Order Date'])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17534 entries, 0 to 17533
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        17534 non-null  object
 1   customer_id     17534 non-null  object
 2   Category        17498 non-null  object
 3   Item            17530 non-null  object
 4   Price           17534 non-null  float64
 5   Quantity        17534 non-null  float64
 6   Order Total     17534 non-null  float64
 7   Order Date      17534 non-null  object
 8   Payment Method  17534 non-null  object
dtypes: float64(3), object(6)
memory usage: 1.2+ MB

In [39]:
df.head()

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
0,ORD_705844,CUST_092,NaN,Side Salad#?,3.0,1.0,3.0,2023-12-21,Credit Card
1,ORD_338528,CUST_021,Side Dishes,Mashed Potatoes,4.0,3.0,12.0,2023-05-19,Digital Wallet
2,ORD_443849,CUST_029,Main Dishes,Grilled Chicken,15.0,4.0,60.0,2023-09-27,Credit Card
3,ORD_630508,CUST_075,Drinks,Water (0.5),-1.0,2.0,2.0,2022-08-09,Credit Card
4,ORD_648269,CUST_031,Main Dishes,Pasta Alfredo,12.0,4.0,48.0,2022-05-15,Cash

#8) Mahsulot nomlarida noto‘g‘ri yoki nomaʼlum belgilar (?, NaN, #) mavjudligini tekshiring va ularni tuzating.

In [40]:
#javobni shu yerda yozing
for idx in lis2:
  df[idx] = df[idx].str.replace(r'[^a-zA-Z\s\d\.]', '', regex = True)

In [41]:
df.sample(5)

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
3697,ORD_697675,CUST_059,Main Dishes,Steak,20.0,4.0,80.0,2023-02-03,Cash
11375,ORD_515178,CUST_060,Desserts,Ice Cream,5.0,5.0,25.0,2022-01-29,Digital Wallet
7079,ORD_225422,CUST_073,Drinks,Water 0.5,-1.0,3.0,3.0,2022-01-24,Digital Wallet
5050,ORD_268267,CUST_024,Side Dishes,Garlic Bread,4.0,3.0,12.0,2023-05-01,Cash
4922,ORD_119071,CUST_001,Starters,Beef Chili,7.0,4.0,28.0,2023-10-25,Cash

#**Maʼlumotlarni filtrlash va qayta ishlash**

#9) Manfiy narx yoki 0 ga teng narx qiymatlarini toping va ularni qanday oʻzgartirish kerakligini hal qiling.

In [42]:
#javobni shu yerda yozing
df[df.Price <= 0].Price.unique()

array([-1.])

In [43]:
df[df.Price<=0] = df[df.Price<=0].replace({-1 : 1, 0 : 1})

In [44]:
df[df.Price<=0]

Empty DataFrame
Columns: [order_id, customer_id, Category, Item, Price, Quantity, Order Total, Order Date, Payment Method]
Index: []

#10) Boʻsh toifalar (kategoriya) mavjudligini tekshiring va toʻgʻri kategoriya berish strategiyasini ishlab chiqing.

In [45]:
#javobni shu yerda yozing
df.Category.isnull().sum()

np.int64(36)

In [46]:
df2 = df[df.Category.isnull()]
df2.sample(10)
df2[df2.Item.isnull()] ### yuqorida narxi 1ga teng bolgan water bor edi va u Drinks categoriyasidan edi.
df.loc[df.Item.isnull()] = df.loc[df.Item.isnull()].fillna({'Category':"Drinks", 'Item':'Water'})

In [72]:
df[df.Category.isnull()]
df.loc[df.Category.isnull(), 'Category'] = df.groupby(['Item', 'Price'])['Category'].transform(
        lambda x: x.fillna(x.mode()[0]) if not x.mode().empty else x

)

In [76]:
df[df.Item == 'Water'].Category.unique()

array(['Drinks'], dtype=object)

#11) Bir xil, lekin turlicha yozilgan qiymatlar (Coffee, cofee, COFEE) mavjudligini tekshiring va tuzating.

In [47]:
#javobni shu yerda yozing
lis2 = ['Category', 'Item', 'Payment Method']
for idx in lis2:
  df[idx] = df[idx].str.title()

#12) `Customer ID` yoki boshqa identifikatorlarning takrorlanishini tekshiring.

In [49]:
#javobni shu yerda yozing
print(df['customer_id'].duplicated().sum())
print(df['order_id'].duplicated().sum())

17434
0

#13) Mahsulotning ortiqcha taʼriflarini olib tashlang (Water (0.5), Water (1.0), Water → faqat Water qoldirish).

In [50]:
#javobni shu yerda yozing
for idx in lis2: ### qavsni 8-vazifada birga belgilar bilan ochirib yuborganman
  df[idx] = df[idx].str.replace(r'[\d\.]', '', regex = True).str.strip()

df.sample(5)

,order_id,customer_id,Category,Item,Price,Quantity,Order Total,Order Date,Payment Method
13785,ORD_548069,CUST_088,Main Dishes,Salmon,18.0,3.0,54.0,2022-10-04,Cash
2860,ORD_859104,CUST_093,Starters,French Fries,4.0,2.0,8.0,2023-12-31,Cash
9409,ORD_169753,CUST_032,Side Dishes,Grilled Vegetables,5.0,3.0,15.0,2022-10-01,Credit Card
7548,ORD_104268,CUST_055,Main Dishes,Vegetarian Platter,14.0,3.0,3.0,2022-04-27,Credit Card
9961,ORD_101024,CUST_077,Starters,Chicken Melt,8.0,5.0,40.0,2022-06-04,Credit Card

#**Qayta ishlangan maʼlumotlar bilan tahlil**

#14) Eng koʻp sotilgan 5 ta mahsulotni aniqlang.

In [51]:
#javobni shu yerda yozing
df.groupby('Item').Quantity.sum().nlargest()

Item
Ice Cream        3640.0
Water            3623.0
Side Salad       3596.0
Pasta Alfredo    3290.0
French Fries     2857.0
Name: Quantity, dtype: float64

#15) Har bir mijoz oʻrtacha qancha pul sarflaganini hisoblang.

In [53]:
#javobni shu yerda yozing
df.groupby('customer_id')['Order Total'].mean()

customer_id
CUST_001    17.120787
CUST_002    18.584746
CUST_003    16.208589
CUST_004    18.456897
CUST_005    17.370253
              ...
CUST_096    18.301546
CUST_097    19.361413
CUST_098    19.008333
CUST_099    19.929448
CUST_100    18.112500
Name: Order Total, Length: 100, dtype: float64

#16) Mijozlarning qaysi kunlarda koʻproq xarid qilgani bo‘yicha tahlil qiling.

In [54]:
#javobni shu yerda yozing
df['Day'] = df['Order Date'].dt.day
df.groupby('Day')['Order Total'].count().nlargest() ## Demak eng kop xaridlar 17, 1, 2, 25, 26 chi kunlari bo'lgan

Day
17    628
1     610
2     610
25    609
26    602
Name: Order Total, dtype: int64

In [55]:
df['Week_day'] = df['Order Date'].dt.day_name()
df.groupby('Week_day')['Order Total'].count().nlargest() ## Demak eng kop xaridlar Juma, Shanba, Dushanba, Payshanba, Yakshanba kunlari bo'lgan

Week_day
Friday      2531
Monday      2526
Saturday    2525
Thursday    2515
Sunday      2483
Name: Order Total, dtype: int64

In [56]:
df.groupby('Order Date')['Order Total'].count().nlargest() ## Demak eng kop xaridlar ushbu sanalarda bo'lgan

Order Date
2023-11-25    42
2022-03-31    41
2022-04-02    40
2023-08-22    40
2023-08-17    37
Name: Order Total, dtype: int64

#17) Narxi oʻrtacha narxdan ikki barobar yuqori boʻlgan mahsulotlarni toping.

In [57]:
#javobni shu yerda yozing
df[df.Price >= 2*df.Price.mean()]['Item']

2           Grilled Chicken
5                    Salmon
7           Grilled Chicken
9        Vegetarian Platter
11                   Salmon
                ...
17480                Salmon
17490                Salmon
17495                 Steak
17505       Grilled Chicken
17506    Vegetarian Platter
Name: Item, Length: 2491, dtype: object

#18) Mahsulotlar kategoriyalari bo‘yicha tahlil qiling va eng ko‘p sotiladigan kategoriyalarni aniqlang.

In [65]:
#javobni shu yerda yozing
df.groupby('Category').agg({'Order Total':'sum'}).sort_values(by='Order Total', ascending=False) ## Demak eng ko'p sotilgan kategoriya bu 1 - Desserts va 2 - Drinks ekan.

             Order Total
Category
Main Dishes     156581.0
Starters         58874.0
Desserts         55866.0
Side Dishes      39962.0
Drinks           22556.5

#19) Har bir mijozning oʻrtacha xarid miqdorini (`groupby("customer_id")`) hisoblang.

In [67]:
#javobni shu yerda yozing
df.groupby('customer_id').Quantity.mean().astype(int)

customer_id
CUST_001    2
CUST_002    3
CUST_003    2
CUST_004    3
CUST_005    2
           ..
CUST_096    2
CUST_097    3
CUST_098    3
CUST_099    2
CUST_100    2
Name: Quantity, Length: 100, dtype: int64

#20) Qanday omillar sotuv hajmiga ta’sir qiladi? Bu bo‘yicha umumiy xulosa chiqaring. Javobni quyida kommentariya sifatida yozing!

In [ ]:
#javobni shu yerda yozing
"""Agar dataframe holatida olsak, pricedagi manfiy qiymatlar yoki 0 kabi sonlar statistik amallarda tasir qiladi. Shuningdek, Ustunlardagi qiymat
turiga ba'zi qiymatlar mos tushmasligi. Masalan, price ustunida matnli qiymatlar mavjud bolib qolishi. Yana Ustunlardagi bitta manoni bildiruvchi qiymatlar
turlicha kiritilishi ham. Misol uchun, Water sozi water, WATER yo Water (0.5) kabi turli xil qiymatlarda kelgan, baxolanki bular hammasi narxda bir xil edi. Shu
kabi muammolarni yechish sotuv hajmi haqida togri malumot berish uchun muhim.

Agar hayotiy tomondan olsak, mahsulotlar kop sotilgani daromadni oshirishi mumkin va mijozlar sonini kopaytirish ham sotuv hajmiga ijobiy tasir qiladi.
"""